/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#a2cfc8",
        "ink-black": "#1A1A1A",
        "on-primary-container": "#7ba8a1",
        "on-tertiary": "#ffffff",
        "slate-gray": "#5F6368",
        "heritage-jade": "#0D3D38",
        "primary-container": "#0d3d38",
        "secondary-container": "#dde0e6",
        "surface": "#fcf9f8",
        "surface-container-high": "#eae7e7",
        "error-container": "#ffdad6",
        "on-background": "#1c1b1b",
        "on-secondary-fixed-variant": "#43474c",
        "secondary": "#5b5f64",
        "on-error": "#ffffff",
        "on-primary-fixed": "#00201d",
        "on-secondary-fixed": "#181c20",
        "on-primary-fixed-variant": "#214e49",
        "surface-container": "#f0eded",
        "primary-fixed": "#bdece4",
        "on-error-container": "#93000a",
        "on-surface": "#1c1b1b",
        "tertiary-fixed": "#ffdbd0",
        "on-secondary": "#ffffff",
        "surface-bright": "#fcf9f8",
        "primary": "#002622",
        "surface-dim": "#dcd9d9",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#313030",
        "primary-fixed-dim": "#a2cfc8",
        "secondary-fixed": "#dfe3e8",
        "tertiary": "#38170c",
        "error": "#ba1a1a",
        "paper-white": "#FCFCFB",
        "surface-container-low": "#f6f3f2",
        "secondary-fixed-dim": "#c3c7cc",
        "on-tertiary-fixed-variant": "#653c2e",
        "outline-variant": "#c0c8c6",
        "muted-silver": "#F8F9FA",
        "tertiary-container": "#522c1f",
        "surface-variant": "#e5e2e1",
        "on-tertiary-container": "#c99281",
        "surface-tint": "#3a6660",
        "surface-container-highest": "#e5e2e1",
        "on-secondary-container": "#5f6368",
        "background": "#fcf9f8",
        "outline": "#707977",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f3f0ef",
        "on-surface-variant": "#404847",
        "tertiary-fixed-dim": "#f4b9a6",
        "on-tertiary-fixed": "#321207",
        "burnt-saffron": "#b85c1c",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "32px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "base": "8px",
        "container-max": "1200px",
        "section-gap": "160px"
      },
      fontFamily: {
        "headline": ["Hanken Grotesk", "Noto Sans Myanmar", "sans-serif"],
        "body": ["Inter", "Noto Sans Myanmar", "sans-serif"],
        "label": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "headline-xl": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "display-lg": ["72px", { "lineHeight": "80px", "letterSpacing": "-0.04em", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "letterSpacing": "0em", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
